### ISSUE TITLE
Flag id for Erzya langauge is presently absent

### ISSUE THREAD

**Issue by rueter** [giellalt/keyboard-myv#1]
**Flag for quick identification of Erzya-language keyboard**

When working with several languages alternately, it saves a lot of time if I can identify the input language by simple coloring instead of a bare keyboard icon.

In earlier Mac versions, there has been a flag present, such as [https://commons.wikimedia.org/wiki/File:Erzya_Flag.svg](https://commons.wikimedia.org/wiki/File:Erzya_Flag.svg)

**Comment by snomos** [comment]
The flag icon is there in the source, just waiting for a new release 🙂 

A new release depends on getting our build infra moved to a new system called TaskCluster. It is done for several core components, and will happen with all `lang-XXX` repositories in the next few days. After that we will take on the keyboards.

@Eijebong is the one responsible for the TaskCluster upgrade.
